version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    volumes:
      - pms:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  pms:
 

networks:
  app_network:
    driver: bridge